// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: doggo-proto/tracker.proto

package Tracker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPointReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat int32 `protobuf:"varint,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon int32 `protobuf:"varint,2,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *AddPointReq) Reset() {
	*x = AddPointReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doggo_proto_tracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointReq) ProtoMessage() {}

func (x *AddPointReq) ProtoReflect() protoreflect.Message {
	mi := &file_doggo_proto_tracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointReq.ProtoReflect.Descriptor instead.
func (*AddPointReq) Descriptor() ([]byte, []int) {
	return file_doggo_proto_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *AddPointReq) GetLat() int32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *AddPointReq) GetLon() int32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type AddPointRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Info string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *AddPointRes) Reset() {
	*x = AddPointRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doggo_proto_tracker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPointRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointRes) ProtoMessage() {}

func (x *AddPointRes) ProtoReflect() protoreflect.Message {
	mi := &file_doggo_proto_tracker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointRes.ProtoReflect.Descriptor instead.
func (*AddPointRes) Descriptor() ([]byte, []int) {
	return file_doggo_proto_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *AddPointRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddPointRes) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_doggo_proto_tracker_proto protoreflect.FileDescriptor

var file_doggo_proto_tracker_proto_rawDesc = []byte{
	0x0a, 0x19, 0x64, 0x6f, 0x67, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x22, 0x31, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x32, 0x43, 0x0a, 0x07, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x14, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42,
	0x0a, 0x5a, 0x08, 0x2f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_doggo_proto_tracker_proto_rawDescOnce sync.Once
	file_doggo_proto_tracker_proto_rawDescData = file_doggo_proto_tracker_proto_rawDesc
)

func file_doggo_proto_tracker_proto_rawDescGZIP() []byte {
	file_doggo_proto_tracker_proto_rawDescOnce.Do(func() {
		file_doggo_proto_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_doggo_proto_tracker_proto_rawDescData)
	})
	return file_doggo_proto_tracker_proto_rawDescData
}

var file_doggo_proto_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_doggo_proto_tracker_proto_goTypes = []interface{}{
	(*AddPointReq)(nil), // 0: Tracker.AddPointReq
	(*AddPointRes)(nil), // 1: Tracker.AddPointRes
}
var file_doggo_proto_tracker_proto_depIdxs = []int32{
	0, // 0: Tracker.Tracker.AddPoint:input_type -> Tracker.AddPointReq
	1, // 1: Tracker.Tracker.AddPoint:output_type -> Tracker.AddPointRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_doggo_proto_tracker_proto_init() }
func file_doggo_proto_tracker_proto_init() {
	if File_doggo_proto_tracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_doggo_proto_tracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPointReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doggo_proto_tracker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPointRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_doggo_proto_tracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doggo_proto_tracker_proto_goTypes,
		DependencyIndexes: file_doggo_proto_tracker_proto_depIdxs,
		MessageInfos:      file_doggo_proto_tracker_proto_msgTypes,
	}.Build()
	File_doggo_proto_tracker_proto = out.File
	file_doggo_proto_tracker_proto_rawDesc = nil
	file_doggo_proto_tracker_proto_goTypes = nil
	file_doggo_proto_tracker_proto_depIdxs = nil
}
